/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BadRequestPage: typeof import('./components/pages/BadRequestPage.vue')['default']
    CharacterCard: typeof import('./components/CharacterCard.vue')['default']
    CharacterPage: typeof import('./components/pages/CharacterPage.vue')['default']
    Comment: typeof import('./components/Comment.vue')['default']
    Header: typeof import('./components/common/Header.vue')['default']
    HomePage: typeof import('./components/pages/HomePage.vue')['default']
    Rating: typeof import('./components/Rating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
